resilience4j.circuitbreaker:
  backends:
    default:
      failureRateThreshold: 50
      ringBufferSizeInClosedState: 5
      ringBufferSizeInHalfOpenState: 5
      waitDurationInOpenState: 20000
      automaticTransitionFromOpenToHalfOpenEnabled: true
      recordExceptions: org.springframework.web.client.HttpServerErrorException,java.io.IOException,java.net.ConnectException,org.springframework.web.client.ResourceAccessException

management.endpoints.web.exposure.include: health,circuitbreakers,metrics
management.endpoint.health.show-details: always

